// <auto-generated />
namespace LIBRARY_MANAGEMENT.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class OrderCreat : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(OrderCreat));
        
        string IMigrationMetadata.Id
        {
            get { return "202002121252097_OrderCreat"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
